[build]
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/financeiro/*"
  to = "/financeiro-dist/:splat"
  status = 200

[[redirects]]
  from = "/financeiro"
  to = "/financeiro-dist/index.html"
  status = 200
